## Shared transport tokens and payload keys for networked game mode.
class_name NetworkProtocol
extends RefCounted

const MSG_GAME_JOIN: StringName = &"game_join"
const MSG_GAME_JOIN_ACK: StringName = &"game_join_ack"
const MSG_GAME_COMMAND: StringName = &"game_command"
const MSG_GAME_SNAPSHOT: StringName = &"game_snapshot"
const MSG_GAME_STATE_UPDATE: StringName = &"game_state_update"
const MSG_ACTION_RESULT: StringName = &"action_result"
const MSG_ERROR: StringName = &"error"
const MSG_PING: StringName = &"ping"
const MSG_PONG: StringName = &"pong"

const CMD_MOVE_N: StringName = &"move_n"
const CMD_MOVE_NE: StringName = &"move_ne"
const CMD_MOVE_SE: StringName = &"move_se"
const CMD_MOVE_S: StringName = &"move_s"
const CMD_MOVE_SW: StringName = &"move_sw"
const CMD_MOVE_NW: StringName = &"move_nw"
const CMD_ATTACK: StringName = &"attack"
const CMD_HEAL: StringName = &"heal"
const CMD_END_TURN: StringName = &"end_turn"
const CMD_NPC_NOOP: StringName = &"npc_noop"

const KEY_TYPE: StringName = &"type"
const KEY_CHANNEL_ID: StringName = &"channel_id"
const KEY_PAYLOAD: StringName = &"payload"
const KEY_COMMAND: StringName = &"command"
const KEY_TARGET_USERNAME: StringName = &"target_username"
const KEY_TIMESTAMP: StringName = &"timestamp"
const KEY_ACTIVE_TURN_USER_ID: StringName = &"active_turn_user_id"
const KEY_PLAYERS: StringName = &"players"
const KEY_OBSTACLES: StringName = &"obstacles"
const KEY_BATTLEFIELD: StringName = &"battlefield"
const KEY_TURN_CONTEXT: StringName = &"turn_context"
const KEY_STATUS_HISTORY: StringName = &"status_history"
const KEY_MAP: StringName = &"map"
const KEY_PROPS: StringName = &"props"

const KEY_SUCCESS: StringName = &"success"
const KEY_ACTION_TYPE: StringName = &"action_type"
const KEY_EXECUTOR_ID: StringName = &"executor_id"
const KEY_EXECUTOR_USERNAME: StringName = &"executor_username"
const KEY_TARGET_ID: StringName = &"target_id"
const KEY_ERROR: StringName = &"error"
const KEY_MESSAGE: StringName = &"message"

const KEY_ACTOR_USER_ID: StringName = &"actor_user_id"
const KEY_ATTACKABLE_TARGET_IDS: StringName = &"attackable_target_ids"
const KEY_SURROUNDINGS: StringName = &"surroundings"
const KEY_SURROUNDINGS_DIFF: StringName = &"surroundings_diff"
const KEY_ADDED: StringName = &"added"
const KEY_REMOVED: StringName = &"removed"
const KEY_CHANGED: StringName = &"changed"
const KEY_ENTITY_ID: StringName = &"entity_id"
const KEY_REVISION: StringName = &"revision"
